name: "Clang Format Lint Action"
author: "Puneet Matharu"
description: "Run clang-format on C++ files"
inputs:
  regex:
    description: "Regex recipe for identifying C++ source files."
    required: false
    default: ^.*\.(c|h|C|H|cpp|hpp|cc|hh|c++|h++|cxx|hxx)$
  version:
    description: "Clang-format version (e.g., '12', '14')."
    required: false
    default: "18"
  style:
    description: "Formatting style."
    required: false
    default: "file"
  inplace:
    description: "Modify files in place."
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Run clang-format
      shell: bash
      run: python3 ${{ github.action_path }}/entrypoint.py --executable="${{ github.action_path }}/clang-format/clang-format${{ inputs.version }}" --style="${{ inputs.style }}" --regex="${{ inputs.regex }}" ${{ inputs.inplace == 'true' && '--inplace' || '' }}
