name: "clang-format lint"
author: "Slobodan Kletnikov (DoozyX)"
description: "Github Action that checks if code is formatted correctly using clang-format"
branding:
  icon: "align-left"
  color: "green"
inputs:
  files:
    description: "Source folder to check formatting"
    required: false
    default: ^.*\.(c|h|C|H|cpp|hpp|cc|hh|c++|h++|cxx|hxx)$
  clangFormatVersion:
    description: "Version of clang-format"
    required: false
    default: "12"
  style:
    description: "Formatting style to use"
    required: false
    default: "file"
  inplace:
    description: "Just fix files (`clang-format -i`) instead of returning a diff"
    required: false
    default: False
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - --clang-format-executable
    - /clang-format/clang-format${{ inputs.clangFormatVersion }}
    - --color
    - always
    - --style
    - ${{ inputs.style }}
    - --inplace
    - ${{ inputs.inplace }}
    - ${{ inputs.files }}
